// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Commit {
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub predecessors: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "4")]
    pub change_id: ::prost::alloc::vec::Vec<u8>,
    /// Alternating positive and negative terms. Set only for conflicts.
    /// Resolved trees are stored in the git commit
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub root_tree: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// TODO(#1624): delete when we assume that all commits use this format
    #[prost(bool, tag = "10")]
    pub uses_tree_conflict_format: bool,
    #[deprecated]
    #[prost(bool, tag = "8")]
    pub is_open: bool,
    #[deprecated]
    #[prost(bool, tag = "9")]
    pub is_pruned: bool,
    /// Hox metadata (fields 11-18)
    ///
    /// 0=Critical, 1=High, 2=Medium, 3=Low
    #[prost(int32, optional, tag = "11")]
    pub priority: ::core::option::Option<i32>,
    /// "open", "in_progress", "blocked", "review", "done", "abandoned"
    #[prost(string, optional, tag = "12")]
    pub status: ::core::option::Option<::prost::alloc::string::String>,
    /// Agent identifier (e.g., "agent-42")
    #[prost(string, optional, tag = "13")]
    pub agent: ::core::option::Option<::prost::alloc::string::String>,
    /// Orchestrator identifier (e.g., "O-A-1")
    #[prost(string, optional, tag = "14")]
    pub orchestrator: ::core::option::Option<::prost::alloc::string::String>,
    /// Message target (supports glob patterns)
    #[prost(string, optional, tag = "15")]
    pub msg_to: ::core::option::Option<::prost::alloc::string::String>,
    /// "mutation", "info", "align_request"
    #[prost(string, optional, tag = "16")]
    pub msg_type: ::core::option::Option<::prost::alloc::string::String>,
    /// Current loop iteration (for Ralph-style loops)
    #[prost(uint32, optional, tag = "17")]
    pub iteration: ::core::option::Option<u32>,
    /// Maximum loop iterations allowed
    #[prost(uint32, optional, tag = "18")]
    pub max_iterations: ::core::option::Option<u32>,
}
